MacOS support
britzl/extension-filedrop pull request #1
Opened 2022-05-15 21:06 UTC by AGulev

2022-05-15 21:08 UTC, AGulev commented on filedrop/src/filedrop_macos.mm
> +    if (dragView == 0)
Unf. we can't set delegate for the main window, so it's easy to create a new invisible view with the same size window has and stretch it together with window.

2022-05-16 07:39 UTC, britzl requested changes
One typo, but otherwise looking good!

2022-05-16 07:39 UTC, britzl commented on filedrop/include/filedrop.h
> +    void FileDrop_Finilize();
Typo: Finilize -> FinAlize

2022-05-16 07:41 UTC, AGulev commented on filedrop/include/filedrop.h
> +    void FileDrop_Finilize();
Thx!

2022-05-16 07:51 UTC, britzl approved these changes

2022-05-16 07:51 UTC, merged